### ISSUE TITLE
[Issue] Massive Bauxite generation

### ISSUE THREAD

**Issue by accessdenied0** [Team-IO/taam#162]
Hey Team-IO,

I wasn't able to get around to recognize the ridiculous amount of Bauxite is generated in my world. It is a bit to much in my opinion. Anyway, I also recognize you forgot to put an option in the config to disable  this generation.

I hope for an update in the future,

access_denied

**Comment by Snipe13051** [comment]
I like the idea and the mashines of the mod but.. i have the same problem with bauxite.. looks ugly like hell (brown) and is everywhere.. even when i try to turn off bauxite they spawn.

 

I use: taam-1.7.10-1.0.1

Problem didn't fixed. 

 

Another question:
Can i use tin, copper ect. from other mods also or can taam handle only tin, iron, copper ect. from taam mod?

Why i can't turn off spawn iron blocks? 

 

Edit:
I didn't understand the name of this mod but the future plans are insane and i hope u wouldn't stop it. I have alot of nice suggestions for your mod to be one of the best factory production mod in mc. 

But i will add them when you asking for it.

 

Thanks

Stefan

 

p.s. Maybe it would help out to get more users to that mod if you also use http://www.minecraftforum.net/

**Comment by founderio** [comment]
Soo, finally I found why people keep complaining!
I just pushed a commit that fixes worldgen settings not applying when they are changed via the GUI config. They would only apply on the next restart of the game.
With this fix, worldgen info is rebuild when the config is changed via the GUI.

Workaround until this fix is published: restart your game after changing the worldgen options, BEFORE generating new chunks/new worlds.

As to your questions @Snipe13051:
Yes, you should be able to use ores, ingots, dusts, etc. from other mods. Taam should be fully compatible, as we try to register everything we can with the ore dictionary.
If you find something that is not compatible but should be, tell us!
Same goes for your suggestions & ideas. Let us know (preferrably one issue per idea/idea group) and we will think about implementing things.
I am not sure what you mean by "Why i can't turn off spawn iron blocks?". Care to elaborate some more? I am not aware of any iron blocks in Taam..

@Xanderio let's discuss the minecraftforum idea, shall we?

**Comment by Snipe13051** [comment]
@founderio 
Iron ores i mean (instead of iron blocks). What almost every other mod also got. 
If taam using alot of normal ores why taam generate his own ores in world generation? 
Especially if you can't turn off the ore generation in .cfg the world is bit overcrowded with ores (especially bauxite ;-) )

I would like to see machines like a scanning mashine and a lift (for belts) for blocks that you can build a production line (like in airports for the passangers baggage). Also if possible a pusher who push the block after it's getting scanned on another belt and maybe a slide block what looks like a slide for childs (chrom colour) where just can blocks sliding down all the way or a small crane (industrie robot) to put blocks from one side to the other side. 


For LATER (addon maybe?):
Another thing what i've not seen yet in factory machines like oil-well pumps, pumpjacks or stuff for gem searching (like here suggested: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/requests-ideas-for-mods/2244622-mod-idea-gold-rush-mod-need-feedback).


Thanks for taking the time and hoping for some response

**Comment by founderio** [comment]
Well.. That is what my correction is all about.
You CAN turn off ore generation (at least for the ores we add in taam. copper, tin, native aluminum, bauxite, ...) -> Possible as of v1.0.1
But at the moment, changing the config via the config GUI will require a game restart. Will be fixed in the next release..

**Comment by founderio** [comment]
@Xanderio Required for final closure of this issue: Lower the default values of bauxite & kaolinite closer to 1.8 andesite, diorite, granite.

**Comment by Snipe13051** [comment]
So there is an *.cfg file where i can adjust it? Because i didn't found one.. maybe i'm just blind.

Can u help me out again? Thanks

**Comment by founderio** [comment]
The file is called taam.cfg in the config folder. (Generates as soon as you start the game once with taam installed.)
You should see a section like this:
`
worldgen {
    # Should Taam generate Aluminum Ore in the World [default: true]
    B:generateAluminum=true

    # Should Taam generate B Ore in the World [default: true]
    B:generateBauxite=true

....
`
This will only apply to new worlds / newly generated chunks, of course. You should edit the file when minecraft is not running.
Likewise you can edit the same config values in the mods-menu, then select taam from the list, then go to config - RESTART the game afterwards, as described some posts above.

**Comment by Snipe13051** [comment]
`worldgen {
    # Should Taam generate Aluminum Ore in the World [default: true]
    B:generateAluminum=true

    # Should Taam generate B Ore in the World [default: true]
    B:generateBauxite=true

    # Should Taam generate Copper Ore in the World [default: true]
    B:generateCopper=true

    # Should Taam generate Kaolinte Ore in the World [default: true]
    B:generateKaolinite=true

    # Should Taam generate Tin Ore in the World [default: true]
    B:generateTin=true

    #  [range: 0 ~ 255, default: 0]
    I:oreAbove_Aluminum=0

    #  [range: 0 ~ 255, default: 0]
    I:oreAbove_Bauxite=0

    #  [range: 0 ~ 255, default: 0]
    I:oreAbove_Copper=0

    #  [range: 0 ~ 255, default: 0]
    I:oreAbove_Kaolinite=0

    #  [range: 0 ~ 255, default: 0]
    I:oreAbove_Tin=0

    #  [range: 0 ~ 255, default: 64]
    I:oreBelow_Aluminum=64

    #  [range: 0 ~ 255, default: 128]
    I:oreBelow_Bauxite=128

    #  [range: 0 ~ 255, default: 64]
    I:oreBelow_Copper=64

    #  [range: 0 ~ 255, default: 100]
    I:oreBelow_Kaolinite=100

    #  [range: 0 ~ 255, default: 64]
    I:oreBelow_Tin=64

    #  [range: 0 ~ 2147483647, default: 64]
    I:oreDepositCount_Aluminum=64

    #  [range: 0 ~ 2147483647, default: 128]
    I:oreDepositCount_Bauxite=128

    #  [range: 0 ~ 2147483647, default: 64]
    I:oreDepositCount_Copper=64

    #  [range: 0 ~ 2147483647, default: 100]
    I:oreDepositCount_Kaolinite=100

    #  [range: 0 ~ 2147483647, default: 64]
    I:oreDepositCount_Tin=64

    #  [range: 0 ~ 2147483647, default: 2]
    I:oreSize_Aluminum=2

    #  [range: 0 ~ 2147483647, default: 35]
    I:oreSize_Bauxite=35

    #  [range: 0 ~ 2147483647, default: 14]
    I:oreSize_Copper=14

    #  [range: 0 ~ 2147483647, default: 35]
    I:oreSize_Kaolinite=35

    #  [range: 0 ~ 2147483647, default: 13]
    I:oreSize_Tin=13
}
`

Sorry didn't found a spoiler.. but what i have to adjust here to set the ore spawn from taam under height 0 (below grass block)? 

Is there a way to do this? 


Because if i turn of bauxite i'm not able to build some machines / stuff from taam i think. So i just need to prevent from spawning in overworld and just let them spawn in underground.

**Comment by Xanderio** [comment]
The Spawning rules for Bauxite are not final.
In the next version Bauxite won't be as annoying as it is now.

btw: you need to change the oreBelow value.

**Comment by founderio** [comment]
@Snipe13051 yes, the oreBelow has to be changed. But do not set it to 0! 0 is the ABSOLUTE 0. Grass usually is around level 60-65. So if you set it to 30 or 40 it should work as you intend.

**Comment by Snipe13051** [comment]
Thanks alot!

Keep up the good work.

**Comment by Xanderio** [comment]
The oregenerator code see brocken eg. copper ignore any value given by the config except the boolean
genOre so the error is probably in line 64 in the OreGenerator class because the boolean gets check by a if in the line above.

**Comment by founderio** [comment]
There was a typo somewhere in the code, always generating copper regardless of which ore was "checked", and another one loading the wrong settings per ore.
Fixed in the next release.
